services:
  app:
    build:
      context: ./drill-and-pratice
      dockerfile: Dockerfile
    image: app
    restart: "no"
    volumes:
      - ./drill-and-pratice:/app
      - ./app-cache:/app-cache
    ports:
      - 7777:7777
    depends_on:
      - postgres
      - flyway
    env_file:
      - .env
    environment:
      - PORT=7777
      - BASE_URL=http://localhost:7777

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${PG_DEV_USER}
      POSTGRES_PASSWORD: ${PG_DEV_PASSWORD}
      POSTGRES_DB: ${PG_DEV_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  flyway:
    image: flyway/flyway:7.3.0-alpine
    depends_on:
      - postgres
    volumes:
      - ./flyway/conf:/flyway/conf
      - ./flyway/sql:/flyway/sql
    command: >
      -configFiles=/flyway/conf/flyway-${FLYWAY_ENV}.conf
      -connectRetries=60
      -baselineOnMigrate=true
      migrate
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  unit-test:
    build:
      context: ./drill-and-pratice
      dockerfile: Dockerfile
    image: app-test
    volumes:
      - ./drill-and-pratice:/app
      - ./app-cache:/app-cache
    depends_on:
      - postgres
    command: deno test --allow-net --allow-env --allow-read --unstable tests/unit
    env_file:
      - .env
    environment:
      - PORT=7777
      - BASE_URL=http://localhost:7777

  integration-test:
    build:
      context: ./drill-and-pratice
      dockerfile: Dockerfile
    image: app-test
    volumes:
      - ./drill-and-pratice:/app
      - ./app-cache:/app-cache
    depends_on:
      - postgres
    command: deno test --allow-net --allow-env --allow-read --unstable tests/integration
    env_file:
      - .env
    environment:
      - PORT=7777
      - BASE_URL=http://localhost:7777

  e2e-tests:
    build:
      context: ./e2e-tests
      dockerfile: Dockerfile
    network_mode: service:app # Attach directly to the app service's network.
    depends_on:
      - app
    volumes:
      - ./e2e-tests/tests:/app/tests
      - ./e2e-tests/playwright-report:/app/playwright-report
    command: sh -c "npx playwright test && cp -r playwright-report /app/playwright-report"
    environment:
      - BASE_URL=http://localhost:7777

  # e2e-tests:
  #   entrypoint: "/bin/true"
  #   build: e2e-tests
  #   network_mode: host
  #   depends_on:
  #     - app
  #   volumes:
  #     - ./e2e-tests/tests:/app/tests
  #     - ./e2e-tests/playwright-report:/app/playwright-report

  # flyway_repair:
  #   image: flyway/flyway:7.3.0-alpine
  #   environment:
  #     - FLYWAY_USER=${FLYWAY_USER}
  #     - FLYWAY_PASSWORD=${FLYWAY_PASSWORD}
  #     - FLYWAY_URL=jdbc:postgresql://postgres:5432/${PG_PROD_DB}
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./flyway/sql:/flyway/sql
  #   command: repair
  #   env_file:
  #     - .env

volumes:
  pgdata:
# services:
#   app:
#     build:
#       context: ./drill-and-pratice
#       dockerfile: Dockerfile
#     image: app
#     restart: "no"
#     volumes:
#       - ./drill-and-pratice:/app
#       - ./app-cache:/app-cache
#     ports:
#       - 7777:7777
#     depends_on:
#       - postgres
#       - flyway
#     env_file:
#       - .env
#     environment:
#       - PORT=7777
#       - BASE_URL=http://localhost:7777

#   postgres:
#     image: postgres:latest
#     container_name: postgres
#     environment:
#       POSTGRES_USER: ${PG_DEV_USER}
#       POSTGRES_PASSWORD: ${PG_DEV_PASSWORD}
#       POSTGRES_DB: ${PG_DEV_DB}
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     ports:
#       - 5432:5432

#   e2e-tests:
#     build:
#       context: ./e2e-tests
#       dockerfile: Dockerfile
#     network_mode: service:app  # Attach directly to the app service's network.
#     depends_on:
#       - app
#     volumes:
#       - ./e2e-tests/tests:/app/tests
#       - ./e2e-tests/playwright-report:/app/playwright-report
#     command: playwright test --project=chromium --reporter=html
#     environment:
#       - BASE_URL=http://localhost:7777

# volumes:
#   pgdata:
