name: Deploy
on:
  push:
    branches: deploy
  pull_request:
    branches: deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Deno Deploy
        run: deno install --allow-read --allow-write --allow-net --unstable https://deno.land/x/deploy/deployctl.ts

      - name: Build step
        run: |
          cd drill-and-pratice 
          deno task build --config=./drill-and-pratice/deno.json

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "drill-and-pratice"
          entrypoint: "run-locally.js"
          root: "drill-and-pratice"
