name: Deploy
on:
  workflow_run:
    workflows: ["Integration && Unit Tests", "Playwright Tests"]
    types:
      - completed
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Check if triggered by workflow_run
        if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
        run: echo "Triggered by successful workflow_run"

      - name: Check if triggered by push or pull_request
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        run: echo "Triggered by push or pull_request"

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "c2495af1-50e0-48ad-a2f1-1ca52c1864ea"
          entrypoint: "run-locally.js"
          root: "drill-and-pratice"
