name: Playwright Tests
on:
  push:
    branches: [main, deploy]
  pull_request:
    branches: [main, deploy]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Npm
        run: npm install
        working-directory: e2e-tests

      - name: Install dependencies
        run: npm ci
        working-directory: e2e-tests

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: e2e-tests

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: e2e-tests

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
