name: Integration Tests with Flyway

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        options: >-
          --health-cmd "pg_isready -U testuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -p 5432 -U testuser; then
              echo "PostgreSQL is ready!";
              break;
            fi;
            echo "Waiting for PostgreSQL...";
            sleep 3;
          done

      - name: Run Flyway migrations
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/flyway/sql:/flyway/sql \
            --network host \
            flyway/flyway:latest \
            -url=jdbc:postgresql://localhost:5432/testdb \
            -user=testuser \
            -password=testpassword \
            migrate

      - name: Run integration tests
        env:
          DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb
          MODE: LOCAL
        run: deno test --allow-net --allow-env --allow-read
